config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :businesses
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :category

  validates :name, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @business = @category.businesses.new
  end
  def create
    @category = Category.find(params[:category_id])
    @business = @category.businesses.new(business_params)
    if @business.save
      redirect_to category_path(@business.category)
    else
      render :new
    end
  end
  def edit
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
    render :edit
  end
  def update
    @category= Category.find(params[:category_id])
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to category_path(@business.category)
    else
      render :edit
    end
  end
  def destroy
    @category = Category.find(params[:category_id])
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to category_path(@business.category)
  end

  private
  def business_params
    params.require(:business).permit(:name, :address, :number, :website)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    render :index
  end
  def show
    @category = Category.find(params[:id])
    render :show
  end
  def new
    @category = Category.new
    render :new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end
  def edit
    @category = Category.find(params[:id])
    render :edit
  end
  def update
    @category= Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render('layouts/errors', :object => @business) %>

<%= form_for [@category, @business] do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :address %>
<%= f.text_field :address %>
<%= f.label :number %>
<%= f.text_field :number %>
<%= f.label :website %>
<%= f.text_field :website %>
<p><%= f.submit %></p>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render "form" %>

app/views/businesses/new.html.erb
<h1>New business for <%= @category.name %></h1>

<%= render 'form' %>

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= form_for @category do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
  <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% if @category.businesses.any? %>
<h4>Here are the businesses for this category:</h4>

<ul>
  <% @category.businesses.each do |business| %>
  <li>
    <%= business.name %> |
    <%= link_to "Edit", edit_category_business_path(@category, business) %> |
    <%= link_to "Delete", category_business_path(@category, business),
    :data => {:confirm => "Are you sure?",
      :method => "delete"} %>
      <br>
    <%= business.address %>
    <br>
    <%= business.number %>
    <br>
    <%= business.website %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p>There are no businesses yet!</p>
  <% end %>

  <p><%= link_to "Add a business", new_category_business_path(@category) %></p>

<p><%= link_to "Edit", edit_category_path(@category) %></p>
<p><%= link_to "Delete", category_path(@category),
:data => {:confirm => "You sure?",
  :method => "delete"} %></p>

<p><%= link_to "Return to categories", categories_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>